Version = "0.1.7"
RequiredFrameworkVersion = "1.4.2"
Prologue = "*该更新由 Github Actions 自动构建于 2025-08-12T05:38:32 并推送"
Items = [

]
Epilogue = ""
DownloadLink = "https://github.com/TwoCreepers/opensvip-plugin-vpr-build-release/releases/download/v0.1.7/opensvip_plugin_vpr_0.1.7.zip"
