Version = "0.2.2"
RequiredFrameworkVersion = "1.4.2"
Date = "2025-08-12"
Prologue = "*该更新由 Github Actions 自动构建于 2025-08-12T12:03:52 并推送"
Items = [

]
Epilogue = ""
DownloadLink = "https://github.com/TwoCreepers/opensvip-plugin-vpr-build-release/releases/download/v0.2.2/opensvip_plugin_vpr_0.2.2.zip"
