Version = "1.0.6"
RequiredFrameworkVersion = "1.4.2"
Date = "2025-09-25"
Prologue = "*该更新由 Github Actions 自动构建于 2025-09-25T12:09:41 (UTC) 并推送"
Items = [

]
Epilogue = ""
DownloadLink = "https://github.com/TwoCreepers/opensvip-plugin-vpr-build-release/releases/download/v1.0.6/opensvip_plugin_vpr_1.0.6.zip"
